site_name: My Project
site_url: https://example.com/
theme:
  name: material
markdown_extensions:
  - pymdownx.superfences
nav:
  - Home: index.md
  - API:
    - Introduction: api/index.md
    - Character: api/character.md
    - City: api/city.md
    - Combat: api/combat.md
    - Dungeon: api/dungeon.md
    - Economic: api/economic.md
    - Equipment: api/equipment.md
    - Gamification: api/gamification.md
    - Inventory: api/inventory.md
    - Progression: api/progression.md
    - Quest: api/quest.md
    - Shop: api/shop.md
    - Travel: api/travel.md
    - World: api/world.md
